INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (1, "The way to get started is to quit talking and begin doing.", "Walt Disney", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (2, "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking.", "Steve Jobs", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (3, "If life were predictable it would cease to be life, and be without flavor.", "Eleanor Roosevelt", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (4, "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.", "Oprah Winfrey", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (5, "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.", "James Cameron", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (6, "Life is what happens when you're busy making other plans.", "John Lennon", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (7, "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "Mother Teresa", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (8, "When you reach the end of your rope, tie a knot in it and hang on.", "Franklin D. Roosevelt", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (9, "Always remember that you are absolutely unique. Just like everyone else.", "Margaret Mead", "");
INSERT OR IGNORE INTO quote (id, quote, author, tags) VALUES (10, "Don't judge each day by the harvest you reap but by the seeds that you plant.", "Robert Louis Stevenson", "");
